package com.cardinalcommerce.a;

import android.content.ContentResolver;
import android.content.Context;
import android.os.Build;
import android.provider.Settings;
import org.json.JSONException;
import org.json.JSONObject;

public final class setForceDarkAllowed {
    private static int getDeviceFingerprint = 0;
    private static int setErrorNumber = 1;
    public int Cardinal;
    public char[] CardinalActionCode;
    public int CardinalChallengeObserver;
    public char[] CardinalConfigurationParameters;
    public char[] CardinalEnvironment;
    public char[] CardinalError;
    public char[] CardinalRenderType;
    public int CardinalUiType;
    public char[] ExtendedData;
    public int Payload;
    public int cca_continue;
    public int cleanup;
    public char[] configure;
    public int getActionCode;
    public int getCavv;
    public char[] getChallengeTimeout;
    public char[] getEciFlag;
    public int getEnrolled;
    public char[] getEnvironment;
    public int getErrorNumber;
    public int getInstance;
    public int getJSON;
    public int getPaResStatus;
    public int getProxyAddress;
    public int getRenderType;
    public char[] getRequestTimeout;
    public char[] getSDKVersion;
    public char[] getSignatureVerification;
    public char[] getString;
    public char[] getThreeDSRequestorAppURL;
    public int getUICustomization;
    public char[] getUiType;
    public char[] getWarnings;
    public char[] getXid;
    public int init;
    public char[] isEnableDFSync;
    public char[] isEnableLogging;
    public char[] isEnabledDiscover;
    public int isEnabledPaypal;
    public char[] isLocationDataConsentGiven;
    public char[] onCReqSuccess;
    public char[] onValidated;
    public int setChallengeTimeout;
    public int setDeviceFingerprint;
    public char[] setEnableDFSync;
    public int setEnableLogging;
    public char[] setEnabledDiscover;
    public int setEnabledPaypal;
    public char[] setEnvironment;
    public int setLocationDataConsentGiven;
    public char[] setProxyAddress;
    public int setRenderType;
    public char[] setRequestTimeout;
    public int setThreeDSRequestorAppURL;
    public int setUICustomization;
    public char[] setUiType;
    public char[] valueOf;
    public char[] values;

    setForceDarkAllowed(Context context) {
        ContentResolver contentResolver = context.getContentResolver();
        this.getInstance = Settings.System.getInt(context.getContentResolver(), "accelerometer_rotation", -1);
        this.Cardinal = Settings.System.getInt(context.getContentResolver(), "bluetooth_discoverability", 0);
        this.init = Settings.System.getInt(context.getContentResolver(), "bluetooth_discoverability_timeout", 0);
        this.cca_continue = Settings.System.getInt(context.getContentResolver(), "date_format", 0);
        this.CardinalConfigurationParameters = setHorizontalScrollBarEnabled.configure(Settings.System.getString(context.getContentResolver(), "dtmf_tone_type"));
        this.configure = setHorizontalScrollBarEnabled.configure(Settings.System.getString(context.getContentResolver(), "dtmf_tone"));
        this.cleanup = Settings.System.getInt(context.getContentResolver(), "end_button_behavior", 0);
        this.onCReqSuccess = setHorizontalScrollBarEnabled.configure(Settings.System.getString(context.getContentResolver(), "font_scale"));
        this.getWarnings = setHorizontalScrollBarEnabled.configure(Settings.System.getString(context.getContentResolver(), "haptic_feedback_enabled"));
        this.onValidated = setHorizontalScrollBarEnabled.configure(Settings.System.getString(context.getContentResolver(), "mode_ringer_streams_affected"));
        this.getSDKVersion = setHorizontalScrollBarEnabled.configure(Settings.System.getString(context.getContentResolver(), "notification_sound"));
        this.CardinalEnvironment = setHorizontalScrollBarEnabled.configure(Settings.System.getString(context.getContentResolver(), "mute_streams_affected"));
        this.CardinalRenderType = setHorizontalScrollBarEnabled.configure(Settings.System.getString(context.getContentResolver(), "ringtone"));
        this.CardinalError = setHorizontalScrollBarEnabled.configure(Settings.System.getString(context.getContentResolver(), "screen_brightness"));
        this.valueOf = setHorizontalScrollBarEnabled.configure(Settings.System.getString(context.getContentResolver(), "screen_brightness_mode"));
        this.values = setHorizontalScrollBarEnabled.configure(Settings.System.getString(context.getContentResolver(), "screen_off_timeout"));
        this.CardinalActionCode = setHorizontalScrollBarEnabled.configure(Settings.System.getString(context.getContentResolver(), "sound_effects_enabled"));
        this.CardinalUiType = Settings.System.getInt(context.getContentResolver(), "auto_caps", 0);
        this.CardinalChallengeObserver = Settings.System.getInt(context.getContentResolver(), "auto_punctuate", -1);
        this.getActionCode = Settings.System.getInt(context.getContentResolver(), "auto_replace", 0);
        this.getString = setHorizontalScrollBarEnabled.configure(Settings.System.getString(context.getContentResolver(), "show_password"));
        this.getRequestTimeout = setHorizontalScrollBarEnabled.configure(Settings.System.getString(context.getContentResolver(), "time_12_24"));
        this.getChallengeTimeout = setHorizontalScrollBarEnabled.configure(Settings.System.getString(context.getContentResolver(), "user_rotation"));
        this.setChallengeTimeout = Settings.System.getInt(context.getContentResolver(), "vibrate_on", 0);
        this.setRequestTimeout = setHorizontalScrollBarEnabled.configure(Settings.System.getString(context.getContentResolver(), "vibrate_when_ringing"));
        this.isEnableLogging = setHorizontalScrollBarEnabled.configure(Settings.Global.getString(contentResolver, "adb_enabled"));
        this.isEnableDFSync = setHorizontalScrollBarEnabled.configure(Settings.Global.getString(contentResolver, "airplane_mode_radios"));
        this.setThreeDSRequestorAppURL = Settings.Global.getInt(contentResolver, "always_finish_activities", 0);
        this.getEnrolled = Settings.Global.getInt(contentResolver, "animator_duration_scale", 1);
        this.getThreeDSRequestorAppURL = setHorizontalScrollBarEnabled.configure(Settings.Global.getString(contentResolver, "auto_time"));
        this.setEnableDFSync = setHorizontalScrollBarEnabled.configure(Settings.Global.getString(contentResolver, "auto_time_zone"));
        this.isLocationDataConsentGiven = setHorizontalScrollBarEnabled.configure(Settings.Global.getString(contentResolver, "development_settings_enabled"));
        this.setEnableLogging = Settings.Global.getInt(contentResolver, "http_proxy", 0);
        this.getJSON = Settings.Global.getInt(contentResolver, "network_preference", 0);
        this.ExtendedData = setHorizontalScrollBarEnabled.configure(Settings.Global.getString(contentResolver, "stay_on_while_plugged_in"));
        this.setLocationDataConsentGiven = Settings.Global.getInt(contentResolver, "transition_animation_scale", 0);
        this.getEciFlag = setHorizontalScrollBarEnabled.configure(Settings.Global.getString(contentResolver, "usb_mass_storage_enabled"));
        this.getPaResStatus = Settings.Global.getInt(contentResolver, "use_google_mail", 0);
        this.getCavv = Settings.Global.getInt(contentResolver, "wait_for_debugger", 0);
        this.getXid = setHorizontalScrollBarEnabled.configure(Settings.Global.getString(contentResolver, "wifi_networks_available_notification_on"));
        this.setEnvironment = setHorizontalScrollBarEnabled.configure(Settings.Secure.getString(contentResolver, "accessibility_enabled"));
        this.getEnvironment = setHorizontalScrollBarEnabled.configure(Settings.Secure.getString(contentResolver, "speak_password"));
        this.getUiType = setHorizontalScrollBarEnabled.configure(Settings.Secure.getString(contentResolver, "allowed_geolocation_origins"));
        this.setProxyAddress = setHorizontalScrollBarEnabled.configure(Settings.Secure.getString(contentResolver, "default_input_method"));
        if (Build.VERSION.SDK_INT <= 33) {
            this.setRenderType = Settings.Secure.getInt(contentResolver, "enabled_input_methods", 0);
        }
        this.getProxyAddress = Settings.Secure.getInt(contentResolver, "input_method_selector_visibility", 0);
        this.setUiType = setHorizontalScrollBarEnabled.configure(Settings.Secure.getString(contentResolver, "install_non_market_apps"));
        this.getErrorNumber = Settings.Secure.getInt(contentResolver, "location_mode", 0);
        this.setEnabledPaypal = Settings.Secure.getInt(contentResolver, "accessibility_display_inversion_enabled", 0);
        this.setDeviceFingerprint = Settings.Secure.getInt(contentResolver, "enabled_accessibility_services", 0);
        this.Payload = Settings.Secure.getInt(contentResolver, "skip_first_use_hints", 0);
        this.getSignatureVerification = null;
        this.isEnabledPaypal = Settings.Secure.getInt(contentResolver, "tts_default_pitch", 0);
        this.setUICustomization = Settings.Secure.getInt(contentResolver, "tts_default_rate", 0);
        this.getRenderType = Settings.Secure.getInt(contentResolver, "tts_default_synth", 0);
        this.getUICustomization = Settings.Secure.getInt(contentResolver, "tts_enabled_plugins", 0);
        if (Build.VERSION.SDK_INT <= 30) {
            this.setEnabledDiscover = setHorizontalScrollBarEnabled.configure(Settings.Global.getString(contentResolver, "data_roaming"));
        }
        this.isEnabledDiscover = setHorizontalScrollBarEnabled.configure(Settings.Secure.getString(contentResolver, "device_provisioned"));
    }

    public final JSONObject getInstance() throws JSONException {
        JSONObject jSONObject = new JSONObject();
        jSONObject.putOpt("AccelerometerRotation", Integer.valueOf(this.getInstance));
        jSONObject.putOpt("BluetoothDiscoverability", Integer.valueOf(this.Cardinal));
        jSONObject.putOpt("BluetoothDiscoverabilityTimeout", Integer.valueOf(this.init));
        jSONObject.putOpt("DateFormat", String.valueOf(this.cca_continue));
        jSONObject.putOpt("DtmfToneWhenDialing", setHorizontalScrollBarEnabled.cca_continue(this.configure));
        jSONObject.putOpt("EndButtonBehavior", String.valueOf(this.cleanup));
        jSONObject.putOpt("FontScale", setHorizontalScrollBarEnabled.cca_continue(this.onCReqSuccess));
        jSONObject.putOpt("HapticFeedbackEnabled", setHorizontalScrollBarEnabled.cca_continue(this.getWarnings));
        jSONObject.putOpt("ModeRingerStreamsAffected", setHorizontalScrollBarEnabled.cca_continue(this.onValidated));
        jSONObject.putOpt("NotificationSound", setHorizontalScrollBarEnabled.cca_continue(this.getSDKVersion));
        jSONObject.putOpt("MuteStreamsAffected", setHorizontalScrollBarEnabled.cca_continue(this.CardinalEnvironment));
        jSONObject.putOpt("Ringtone", setHorizontalScrollBarEnabled.cca_continue(this.CardinalRenderType));
        jSONObject.putOpt("ScreenBrightness", setHorizontalScrollBarEnabled.cca_continue(this.CardinalError));
        jSONObject.putOpt("ScreenBrightnessMode", setHorizontalScrollBarEnabled.cca_continue(this.valueOf));
        jSONObject.putOpt("ScreenOffTimeout", setHorizontalScrollBarEnabled.cca_continue(this.values));
        jSONObject.putOpt("SoundEffectsEnabled", setHorizontalScrollBarEnabled.cca_continue(this.CardinalActionCode));
        jSONObject.putOpt("TextAutoCaps", String.valueOf(this.CardinalUiType));
        jSONObject.putOpt("TextAutoPunctuate", Integer.valueOf(this.CardinalChallengeObserver));
        jSONObject.putOpt("TextAutoReplace", String.valueOf(this.getActionCode));
        jSONObject.putOpt("TextShowPassword", setHorizontalScrollBarEnabled.cca_continue(this.getString));
        jSONObject.putOpt("Time1224", setHorizontalScrollBarEnabled.cca_continue(this.getRequestTimeout));
        jSONObject.putOpt("UserRotation", setHorizontalScrollBarEnabled.cca_continue(this.getChallengeTimeout));
        jSONObject.putOpt("VibrateOn", String.valueOf(this.setChallengeTimeout));
        jSONObject.putOpt("VibrateWhenRinging", setHorizontalScrollBarEnabled.cca_continue(this.setRequestTimeout));
        jSONObject.putOpt("DtmfToneTypeWhenDialing", setHorizontalScrollBarEnabled.cca_continue(this.CardinalConfigurationParameters));
        jSONObject.putOpt("AccessibilityEnabled", setHorizontalScrollBarEnabled.cca_continue(this.setEnvironment));
        jSONObject.putOpt("AccessibilitySpeakPassword", setHorizontalScrollBarEnabled.cca_continue(this.getEnvironment));
        jSONObject.putOpt("AllowedGeolocationOrigins", setHorizontalScrollBarEnabled.cca_continue(this.getUiType));
        jSONObject.putOpt("DefaultInputMethod", setHorizontalScrollBarEnabled.cca_continue(this.setProxyAddress));
        jSONObject.putOpt("InputMethodSelectorVisibility", String.valueOf(this.getProxyAddress));
        jSONObject.putOpt("EnabledInputMethods", String.valueOf(this.setRenderType));
        jSONObject.putOpt("InstallNonMarketApps", setHorizontalScrollBarEnabled.cca_continue(this.setUiType));
        jSONObject.putOpt("TtsDefaultRate", String.valueOf(this.setUICustomization));
        jSONObject.putOpt("TtsDefaultSynth", String.valueOf(this.getRenderType));
        jSONObject.putOpt("TtsEnabledPlugins", String.valueOf(this.getUICustomization));
        jSONObject.putOpt("AdbEnabled", setHorizontalScrollBarEnabled.cca_continue(this.isEnableLogging));
        jSONObject.putOpt("AirplaneModeRadios", setHorizontalScrollBarEnabled.cca_continue(this.isEnableDFSync));
        jSONObject.putOpt("AlwaysFinishActivities", String.valueOf(this.setThreeDSRequestorAppURL));
        jSONObject.putOpt("AutoTime", setHorizontalScrollBarEnabled.cca_continue(this.getThreeDSRequestorAppURL));
        jSONObject.putOpt("AutoTimeZone", setHorizontalScrollBarEnabled.cca_continue(this.setEnableDFSync));
        jSONObject.putOpt("DevelopmentSettingsEnabled", setHorizontalScrollBarEnabled.cca_continue(this.isLocationDataConsentGiven));
        jSONObject.putOpt("HttpProxy", String.valueOf(this.setEnableLogging));
        jSONObject.putOpt("NetworkPreference", String.valueOf(this.getJSON));
        jSONObject.putOpt("StayOnWhilePluggedIn", setHorizontalScrollBarEnabled.cca_continue(this.ExtendedData));
        jSONObject.putOpt("TransitionAnimationScale", Integer.valueOf(this.setLocationDataConsentGiven));
        jSONObject.putOpt("UsbMassStorageEnabled", setHorizontalScrollBarEnabled.cca_continue(this.getEciFlag));
        jSONObject.putOpt("UseGoogleMail", String.valueOf(this.getPaResStatus));
        jSONObject.putOpt("WaitForDebugger", String.valueOf(this.getCavv));
        jSONObject.putOpt("WifiNetworksAvailableNotificationOn", setHorizontalScrollBarEnabled.cca_continue(this.getXid));
        jSONObject.putOpt("AnimatorDurationScale", String.valueOf(this.getEnrolled));
        jSONObject.putOpt("DataRoaming", setHorizontalScrollBarEnabled.cca_continue(this.setEnabledDiscover));
        jSONObject.putOpt("DeviceProvisioned", setHorizontalScrollBarEnabled.cca_continue(this.isEnabledDiscover));
        jSONObject.putOpt("TtsDefaultPitch", String.valueOf(this.isEnabledPaypal));
        jSONObject.putOpt("SysPropSettingVersion", setHorizontalScrollBarEnabled.cca_continue(this.getSignatureVerification));
        jSONObject.putOpt("SkipFirstUseHints", String.valueOf(this.Payload));
        jSONObject.putOpt("EnabledAccessibilityServices", String.valueOf(this.setDeviceFingerprint));
        jSONObject.putOpt("AccessibilityDisplayInversionEnabled", String.valueOf(this.setEnabledPaypal));
        jSONObject.putOpt("LocationMode", String.valueOf(this.getErrorNumber));
        int i = getDeviceFingerprint;
        int i2 = i & 25;
        int i3 = ((i ^ 25) | i2) << 1;
        int i4 = -((i | 25) & (~i2));
        int i5 = (i3 ^ i4) + ((i4 & i3) << 1);
        setErrorNumber = i5 % 128;
        if ((i5 % 2 == 0 ? 7 : '9') != 7) {
            return jSONObject;
        }
        Throwable th = null;
        super.hashCode();
        throw th;
    }
}
